<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260216212301 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        // this up() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE ticket_ai_analysis_feedback (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, decision VARCHAR(255) NOT NULL, comment TEXT DEFAULT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, analysis_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX IDX_197CA20F7941003F ON ticket_ai_analysis_feedback (analysis_id)');
        $this->addSql('ALTER TABLE ticket_ai_analysis_feedback ADD CONSTRAINT FK_197CA20F7941003F FOREIGN KEY (analysis_id) REFERENCES ticket_analysis (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('ALTER TABLE ticket_ai_analysis_feedback DROP CONSTRAINT FK_197CA20F7941003F');
        $this->addSql('DROP TABLE ticket_ai_analysis_feedback');
    }
}
